name: Release

on:
  release:
    types: [published]

jobs:

  release_zip:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Zip openmediavault dir
        run: |
          cd ${{ github.workspace }}/custom_components/openmediavault
          zip openmediavault.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/openmediavault/openmediavault.zip
          asset_name: openmediavault.zip
          tag: ${{ github.ref }}
          overwrite: true
